security:
    providers:
        from_database:
            entity:
                class: App\Entity\User
                property: mail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
                login_path: connexion
                check_path: connexion
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/compte, roles: ROLE_USER }
        - { path: ^/forum/create, roles: ROLE_USER }
        - { path: ^/tutorial/create, roles: ROLE_USER }
        - { path: ^/tutorial/like, roles: ROLE_USER }
        - { path: ^/tutorial/unlike, roles: ROLE_USER }
        - { path: ^/forum/unlike, roles: ROLE_USER }
        - { path: ^/forum/like, roles: ROLE_USER }
        - { path: ^/report, roles: ROLE_USER }
        - { path: ^/forum/suggestion, roles: ROLE_USER }
        - { path: ^/tutorial/suggestion, roles: ROLE_USER }
        - { path: ^/forum/report, roles: ROLE_USER }
        - { path: ^/tutorial/report, roles: ROLE_USER }

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12