vich_uploader:
    db_driver: orm

    mappings:
        user_filename:
            uri_prefix: /Images/account_pictures
            upload_destination: '%kernel.project_dir%/public/Images/account_pictures'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug'}