#!/bin/bash
rsync -av -e "ssh -p 22" ./ root@192.168.1.21:/var/www/commentfaire/ --exclude-from=.gitignore --exclude=".*";
ssh root@192.168.1.21 'cd /var/www/commentfaire && composer install --no-dev --optimize-autoloader && php bin/console cache:clear && sudo chmod -R 777 *'